WIP: fix for null oopMap
offamitkumar/jdk pull request #3
Opened 2023-05-29 12:33 UTC by offamitkumar

Doesn't fix the issue as of now, but you may want to pick it from here...

2023-05-29 12:34 UTC, offamitkumar commented
`wget/curl` diff file from here: https://patch-diff.githubusercontent.com/raw/offamitkumar/jdk/pull/3.diff

2023-06-01 15:46 UTC, offamitkumar commented
@backwaterred could you make it to merge by today, with our personal master branch ???

2023-06-01 17:21 UTC, backwaterred requested changes

2023-06-01 17:21 UTC, backwaterred commented on src/hotspot/cpu/s390/sharedRuntime_s390.cpp
> +  const int framesize_bytes = frame::z_abi_160_size; /*I think pushing a frame is not a good idea*/
> /*I think pushing a frame is not a good idea*/

Why not a good idea? In my understanding we need one for the oopmap to work.

RR's suggestion was to use `const int framesize_bytes = __ push_frame_abi160(0);` to set the frame size. If you check the implementation of the push_frame procedure, it actually takes care of alignment as well, then returns the final size. I thought this was a nice improvement over the way ppc does it.

2023-06-01 17:21 UTC, backwaterred commented on src/hotspot/cpu/s390/sharedRuntime_s390.cpp
> +  OopMap* map = new OopMap(framesize_bytes / VMRegImpl::stack_slot_size, 0);
Niiiice :-)

2023-06-01 17:30 UTC, offamitkumar commented on src/hotspot/cpu/s390/sharedRuntime_s390.cpp
> +  const int framesize_bytes = frame::z_abi_160_size; /*I think pushing a frame is not a good idea*/
I think we are already pushing the frame at Line 1611

2023-06-01 17:32 UTC, offamitkumar commented on src/hotspot/share/runtime/continuationFreezeThaw.cpp
> +         "SharedRuntime::cont_doYield_stub()->frame_size(): %d and doYield_stub_frame_size: %d must be equal", SharedRuntime::cont_doYield_stub()->frame_size(), doYield_stub_frame_size);
I think we can improve this message, not sure how. Any better suggestion ?

2023-06-01 22:56 UTC, backwaterred commented on src/hotspot/cpu/s390/sharedRuntime_s390.cpp
> +  const int framesize_bytes = frame::z_abi_160_size; /*I think pushing a frame is not a good idea*/
Yeah, but if we need to push a frame (and are pushing it later). why would we push changes that suggest it's a bad idea?

2023-06-01 22:57 UTC, backwaterred commented on src/hotspot/cpu/s390/sharedRuntime_s390.cpp
> +  const int framesize_bytes = frame::z_abi_160_size; /*I think pushing a frame is not a good idea*/
Also, I'm a fan of keeping the changes that RR suggested here.

2023-06-01 23:01 UTC, backwaterred commented on src/hotspot/share/runtime/continuationFreezeThaw.cpp
> +         "SharedRuntime::cont_doYield_stub()->frame_size(): %d and doYield_stub_frame_size: %d must be equal", SharedRuntime::cont_doYield_stub()->frame_size(), doYield_stub_frame_size);
No suggestions. I think we may end up reverting common code changes to assert statements (or doing them in a separate pass).

2023-06-02 09:18 UTC, offamitkumar commented on src/hotspot/cpu/s390/sharedRuntime_s390.cpp
> +  const int framesize_bytes = frame::z_abi_160_size; /*I think pushing a frame is not a good idea*/
>Yeah, but if we need to push a frame (and are pushing it later). why would we push changes that suggest it's a bad idea? 

removed..

>I'm a fan of keeping the changes that RR suggested here.


which change I removed ?

2023-06-02 21:01 UTC, backwaterred requested changes

2023-06-02 21:01 UTC, backwaterred commented on src/hotspot/cpu/s390/sharedRuntime_s390.cpp
> -  framesize_words = framesize_bytes / wordSize;
Keep this

2023-06-02 21:01 UTC, backwaterred commented on src/hotspot/cpu/s390/sharedRuntime_s390.cpp
> +  __ push_frame_abi160(framesize_bytes);
Drop this

2023-06-02 21:01 UTC, backwaterred commented on src/hotspot/cpu/s390/sharedRuntime_s390.cpp
> +  framesize_words = framesize_bytes / wordSize;
Drop this

2023-06-02 21:02 UTC, backwaterred commented on src/hotspot/cpu/s390/sharedRuntime_s390.cpp
> +  const int framesize_bytes = frame::z_abi_160_size; /*I think pushing a frame is not a good idea*/
> > I'm a fan of keeping the changes that RR suggested here.

> which change I removed ?

I marked them in another review.

2023-06-02 21:04 UTC, backwaterred commented
I think these changes are mostly good. But, I want to keep the changes that I made in my last PR. I tagged them in a review above.

2023-06-02 21:58 UTC, backwaterred commented on src/hotspot/share/runtime/continuationFreezeThaw.cpp
> -  static const int doYield_stub_frame_size = frame::metadata_words;
Should metadata words be changed to `sizeof(z_abi_160_base) << ...` and be used here?

2023-06-02 22:14 UTC, backwaterred commented on src/hotspot/share/runtime/continuationFreezeThaw.cpp
> +#if defined(PPC64)
I think this needs to be `#if defined(PPC64) && !defined(ZERO)` to match the previous logic.

2023-06-05 20:29 UTC, backwaterred approved these changes

2023-06-06 04:11 UTC, merged